name: Tests
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false

      matrix:
        node-version: [14.x]
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install

      - name: TypeScript
        run: yarn tsc

      - name: ESLint
        run: yarn lint

      - name: Prettier
        run: yarn format
